[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  package = "netlify-plugin-nextjs"
  package = "netlify-plugin-lighthouse"
  package = "netlify-plugin-chromium"